# Generated by Django 4.0.5 on 2022-07-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50, verbose_name='Название города')),
                ('days', models.FloatField(max_length=20, verbose_name='Количество дней')),
            ],
            options={
                'verbose_name': 'Название города',
                'verbose_name_plural': 'Название городов',
                'ordering': ['name_city'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_package', models.CharField(db_index=True, max_length=30, verbose_name='Вариант упаковки')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('compound', models.TextField(blank=True, verbose_name='Состав')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ассортимен',
                'verbose_name_plural': 'Ассортимент',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Storage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_prod', models.IntegerField(max_length=20, verbose_name='Количество')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.production', verbose_name='Продукция')),
            ],
        ),
        migrations.CreateModel(
            name='Storage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_prod', models.IntegerField(max_length=20, verbose_name='Количество')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.production', verbose_name='Продукция')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=20, verbose_name='Стоимость')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.package', verbose_name='Вариант упаковки')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.production', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимость',
                'ordering': ['prod', 'pack', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Factory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField(max_length=20, verbose_name='Количество дней')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.package', verbose_name='Вариант упаковки')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.production', verbose_name='Продукция')),
            ],
        ),
        migrations.CreateModel(
            name='Factory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField(max_length=20, verbose_name='Количество дней')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.package', verbose_name='Вариант упаковки')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candy_shop_app.production', verbose_name='Продукция')),
            ],
        ),
    ]
