# Generated by Django 4.0.5 on 2022-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory1',
            options={'ordering': ['prod', 'days'], 'verbose_name': 'Фабрика 1', 'verbose_name_plural': 'Фабрика 1'},
        ),
        migrations.AlterModelOptions(
            name='factory2',
            options={'ordering': ['prod', 'days'], 'verbose_name': 'Фабрика 2', 'verbose_name_plural': 'Фабрика 2'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name_package'], 'verbose_name': 'Упаковка', 'verbose_name_plural': 'Упаковки'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['name_prod'], 'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортимент'},
        ),
        migrations.AlterModelOptions(
            name='storage1',
            options={'ordering': ['prod'], 'verbose_name': 'Склад 1', 'verbose_name_plural': 'Склад 1'},
        ),
        migrations.AlterModelOptions(
            name='storage2',
            options={'ordering': ['prod'], 'verbose_name': 'Склад 2', 'verbose_name_plural': 'Склад 2'},
        ),
        migrations.RenameField(
            model_name='production',
            old_name='title',
            new_name='name_prod',
        ),
        migrations.AlterField(
            model_name='storage1',
            name='count_prod',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storage2',
            name='count_prod',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
