# Generated by Django 4.0.6 on 2022-08-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['name_prod'], 'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортимент'},
        ),
    ]
